### ISSUE TITLE
Resolving dependency issues

### ISSUE THREAD

**Issue by callifo** [SAIC-iSmart-API/saic-python-mqtt-gateway#274]
Trying to install the newer versions of saic-python-mqtt-gateway (0.6.3) after having remained on an ancient version for Australia (saic_ismart_client not saic_ismart_client_ng) but having a lot of problem with dependencies. 

Initially tried to use Python3.12 venv to run saic-python-mqtt-gateway however 
```
cannot import 'ChrgMgmtDataResp' from 
/opt/saic-python-mqtt-gateway-ng/lib/python3.11/site-packages/saic_ismart_client_ng/api/vehicle_charging/__init__.py
```

For whatever reason, the version of saic_ismart_client_ng that pip downloads for Python 3.12 does not contain ChrgMgmtDataResp, whereas Python3.11 does. So I switched back to Python 3.11 as that is what my previous version was using. However hit the next dependency issue,

```
Traceback (most recent call last):
  File "/opt/saic-python-mqtt-gateway-ng/saic-python-mqtt-gateway/mqtt_gateway.py", line 12, in <module>
    from typing import Callable, override
ImportError: cannot import name 'override' from 'typing' (/usr/local/lib/python3.11/typing.py)
```
Any suggestions where to go for this one? Debian 12 wont allow me to install it into the base Python 3.11, and install it into the venv does not work.

**Comment by callifo** [comment]
Worked out I made a mistake with python 3.12, and it wouldnt work with 3.11 any more due to the requirements.
